services:
    caddy:
        image: caddy:latest
        container_name: caddy
        restart: unless-stopped
        ports:
            - "9999:9999"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
        networks:
            - backend

    api01:
        build:
            context: .
            dockerfile: Dockerfile
        image: leoralph/rinha-de-backend-2025
        networks:
            - backend
            - payment-processor
        depends_on:
            - redis

    api02:
        build:
            context: .
            dockerfile: Dockerfile
        image: leoralph/rinha-de-backend-2025
        networks:
            - backend
            - payment-processor
        depends_on:
            - redis
    api03:
        build:
            context: .
            dockerfile: Dockerfile
        image: leoralph/rinha-de-backend-2025
        networks:
            - backend
            - payment-processor
        depends_on:
            - redis

    api04:
        build:
            context: .
            dockerfile: Dockerfile
        image: leoralph/rinha-de-backend-2025
        networks:
            - backend
            - payment-processor
        depends_on:
            - redis

    redis:
        image: redis:latest
        networks:
            - backend
        deploy:
            resources:
                limits:
                    cpus: "0.3"
                    memory: 50M

networks:
    backend:
        driver: bridge
    payment-processor:
        external: true
