services:
  backend:
    build: .
    image: leoralph/rinha-de-backend-2025
    ports:
      - "9999:8000"
    networks:
      - backend
      - payment-processor

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
